name = "LinearPowerFlow"
uuid = "065002bc-66a7-4ca6-850a-9d9c9ecf15c6"
authors = ["Nick Laws <laws.nick@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
